name: Operationsyncplugin
version: ${project.version}
main: net.kunmc.lab.operationsyncplugin.Operationsyncplugin
api-version: 1.15
description: 操作シンクロプラグイン
depend: [ProtocolLib]

commands:
  sync:
    description: Operationsync Plugin commands
    aliases: o1
    permission: sync.manage
permissions:
  sync.manage:
    description: operation sync
    default: op